name: 'GitHub Commit Stats'
description: 'Add commit statistics to your GitHub Profile README'
author: 'VatsalSy'

inputs:
  GH_COMMIT_TOKEN:
    description: 'GitHub Personal Access Token'
    required: true
  SHOW_COMMIT:
    description: 'Show commit timing patterns'
    required: false
    default: 'true'
  SHOW_DAYS_OF_WEEK:
    description: 'Show most productive days'
    required: false
    default: 'true'
  COMMIT_MESSAGE:
    description: 'Custom commit message'
    required: false
    default: 'docs(stats): update github stats'
  COMMIT_BY_ME:
    description: 'Whether commits should be authored by the token owner'
    required: false
    default: 'false'
  COMMIT_USERNAME:
    description: 'Username for commit author'
    required: false
    default: 'github-actions[bot]'
  COMMIT_EMAIL:
    description: 'Email for commit author'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'

runs:
  using: 'composite'
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "${{ inputs.COMMIT_USERNAME }}"
        git config --global user.email "${{ inputs.COMMIT_EMAIL }}"
        
        # Use credential helper instead of token in URL
        git config --global credential.helper store
        echo "https://oauth2:${{ inputs.GH_COMMIT_TOKEN }}@github.com" > ~/.git-credentials
        chmod 600 ~/.git-credentials

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run stats update
      shell: bash
      env:
        INPUT_GH_COMMIT_TOKEN: ${{ inputs.GH_COMMIT_TOKEN }}
        GITHUB_TOKEN: ${{ inputs.GH_COMMIT_TOKEN }}
        DEBUG_RUN: 'false'
        SHOW_COMMIT: ${{ inputs.SHOW_COMMIT }}
        SHOW_DAYS_OF_WEEK: ${{ inputs.SHOW_DAYS_OF_WEEK }}
        COMMIT_MESSAGE: ${{ inputs.COMMIT_MESSAGE }}
        COMMIT_BY_ME: ${{ inputs.COMMIT_BY_ME }}
        COMMIT_USERNAME: ${{ inputs.COMMIT_USERNAME }}
        COMMIT_EMAIL: ${{ inputs.COMMIT_EMAIL }}
      working-directory: ${{ github.action_path }}
      run: |
        cd ${{ github.action_path }}
        python -m sources.main