name: 'GitHub Commit Statistics'
author: Vatsal Sanjay
description: 'When are you most productive during the week? Let''s check out in your readme!'

inputs:
  GH_TOKEN:
    description: 'GitHub access token with Repo scope'
    required: true
    default: ${{ github.token }}

  SECTION_NAME:
    description: 'Name used in readme to scope the updated section'
    required: false
    default: "github-stats"

  SHOW_COMMIT:
    required: false
    description: "Shows the number of commit graph in the dev metrics"
    default: "True"

  SHOW_DAYS_OF_WEEK:
    required: false
    description: "show day of week you are most productive"
    default: "True"

  COMMIT_BY_ME:
    required: false
    description: "Git commit with your own name and email"
    default: "False"
  
  COMMIT_MESSAGE:
    required: false
    description: "Git commit message"
    default: "Updated with Dev Metrics"

runs:
  using: 'docker'
  image: 'docker://ghcr.io/vatsalsanjay/github-stats:master'

branding:
  icon: 'activity'
  color: 'orange'
